<a href="https://colab.research.google.com/github/DDinggi/-/blob/main/ex03_evalue%2Bevector2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import numpy.linalg as npl
import matplotlib.pyplot as plt

In [5]:
A = np.array([[4,2], [1,3]])
print("A:")
print(A, "\n")

e_values, e_vectors = npl.eig(A)
print("A의 고윳값 = ", e_values)
print("A의 고유벡터 = ", e_vectors)

u1 = np.vstack(e_vectors[:, 0])
u2 = np.vstack(e_vectors[:,1])
print("u1: ", u1)
print("u2: ", u2)

l1, l2 = e_values[0], e_values[1]
print("eigen values: ", l1, l2, "\n")

print ("Au1: ", np.dot(A, u1))
print ("l1*u1: ", l1 * u1)

print ("Au2: ", np.dot(A, u2))
print("l2*u2: ", l2*u2)

A:
[[4 2]
 [1 3]] 

A의 고윳값 =  [5. 2.]
A의 고유벡터 =  [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
u1:  [[0.89442719]
 [0.4472136 ]]
u2:  [[-0.70710678]
 [ 0.70710678]]
eigen values:  5.0 2.0 

Au1:  [[4.47213595]
 [2.23606798]]
l1*u1:  [[4.47213595]
 [2.23606798]]
Au2:  [[-1.41421356]
 [ 1.41421356]]
l2*u2:  [[-1.41421356]
 [ 1.41421356]]


In [6]:
B = np.array([[5,2,0], [2,5,0], [-3, 4, 6]])
w2, V2 = np.linalg.eig(B)

print("\nB의 고윳값= ", w2)
print("B의 고유벡터= ", V2)


B의 고윳값=  [6. 7. 3.]
B의 고유벡터=  [[ 0.          0.57735027  0.36650833]
 [ 0.          0.57735027 -0.36650833]
 [ 1.          0.57735027  0.85518611]]
